import{a as g,S as L,i as w}from"./assets/vendor-DXaqCXe3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const b="49383034-f250c1a79c2ac8474ecbb0034",S="https://pixabay.com/api/",f=async(t,r=1,o=15)=>{try{return(await g.get(S,{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:o}})).data}catch(n){throw console.error("Error fetching images:",n),n}},m=document.querySelector(".gallery"),v=document.querySelector(".load-more"),q=()=>{m.innerHTML=""},p=()=>{document.querySelector(".loader").style.display="block"},l=()=>{document.querySelector(".loader").style.display="none"};function h(t){const r=t.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}" class="gallery-link">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),new L(".gallery a").refresh()}const d=()=>{w.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})},u=t=>{v.style.display=t?"block":"none"},$=()=>{const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},E=document.querySelector(".form"),M=document.querySelector(".load-more");let c="",a=1;const y=15;E.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements["search-text"].value.trim(),!!c){q(),u(!1),a=1,p();try{const{hits:r,totalHits:o}=await f(c,a,y);if(l(),r.length===0){d();return}h(r),u(r.length<o)}catch{l(),d()}}});M.addEventListener("click",async()=>{a+=1,p();try{const{hits:t,totalHits:r}=await f(c,a,y);l(),h(t),$(),a*y>=r&&(u(!1),iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{l(),d()}});
//# sourceMappingURL=index.js.map
